import type { BookFormat, ThemeMode, CustomTheme } from '../types'

/** Universal location returned by adapters. For epub: CFI string. For txt/mobi: 'chapterIdx:charOffset' */
export interface BookLocation {
  format: BookFormat
  /** For epub: CFI. For txt/mobi: 'chapterIdx:charOffset' */
  location: string
  /** 0-based chapter index */
  chapterIdx: number
  /** 0-100 percent */
  progress: number
  /** Human-readable chapter title (optional) */
  chapterLabel?: string
}

export interface TocItem {
  label: string
  /** Location string usable with goToLocation() */
  location: string
  subitems?: TocItem[]
}

export interface SearchResult {
  /** Location string usable with goToLocation() to jump to match */
  location: string
  /** Chapter label where match was found */
  label: string
  /** Surrounding context for display */
  excerpt: string
}

export interface HighlightSpec {
  /** For epub: CFI range. For txt/mobi: 'chapterIdx:startOffset-endOffset' */
  location: string
  /** Selected text (used as fallback for search/display) */
  text: string
  /** Color string (hex/rgba) */
  color: string
}

export interface SelectionInfo {
  selectedText: string
  /** If null, user has not selected anything */
  range: HighlightSpec | null
}

export interface BookAdapter {
  /** Format this adapter handles */
  readonly format: BookFormat

  /**
   * Open a book and render into the given container element.
   * Must be called before any other method.
   */
  open(filePath: string, container: HTMLElement): Promise<void>

  /**
   * Release all resources. Safe to call multiple times.
   */
  destroy(): void

  // ---- Navigation ----

  /** Advance to next page/section */
  next(): Promise<void>
  /** Go back to previous page/section */
  prev(): Promise<void>
  /** Jump to a specific location (format-specific) */
  goToLocation(location: string): Promise<void>
  /** Current location (used for progress sync) */
  getCurrentLocation(): BookLocation

  // ---- Content ----

  /** Get table of contents */
  getToc(): TocItem[]
  /** Get text of a specific chapter (0-indexed) */
  getChapterText(idx: number): Promise<string>
  /** Get the full book text (for full-text search indexing) */
  getFullText(): Promise<string>
  /** Total number of chapters/sections */
  getChapterCount(): number

  // ---- Search ----

  /** Search for a query string. Case-insensitive. */
  search(query: string): Promise<SearchResult[]>

  // ---- Annotations ----

  /** Add a highlight. ID is generated by adapter and returned for later removal. */
  addHighlight(spec: HighlightSpec): Promise<string>
  /** Remove a previously added highlight by ID */
  removeHighlight(id: string): Promise<void>
  /** Clear all highlights (called before re-rendering saved highlights) */
  clearHighlights(): void

  // ---- Theming ----

  /** Apply one of the 3 built-in themes. */
  applyTheme(theme: ThemeMode): void
  /** Apply user-defined custom theme CSS. */
  applyCustomThemeCSS(css: string): void

  // ---- Selection ----

  /** Get current user selection (text + location range). */
  getSelectionInfo(): SelectionInfo
}
